
import com.mysql.jdbc.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hp
 */
public class TakeMoreOrders extends javax.swing.JFrame {

    /**
     * Creates new form TakeMoreOrders
     */
    String eid;
     String e="noemp";
    Connection c1=null;
        PreparedStatement pst=null;
        ResultSet s=null;
    public TakeMoreOrders(String id1) {
        initComponents();
        pid.setText("");
        o1.setText("");
        dest1.setText("");
        content1.setText("");
        
        this.setLocationRelativeTo(null);
        this.eid=id1;
        try
        { 
           c1=(Connection) MyConnection.connect();
            String query="SELECT prod_id,origin,destination,sender_name,sender_no,receiver_no,content,days,status FROM employee_orders WHERE emp_uname='"+e+"'";
             pst=(com.mysql.jdbc.PreparedStatement) c1.prepareStatement(query);
            s=pst.executeQuery();
            while(s.next())
            {
                String pid=s.getString(1);
                String origin=s.getString(2);
                String destination=s.getString(3);
                String name1=s.getString(4);
                String phone1=s.getString(5);
                String phone2=s.getString(6);
                String c=s.getString(7);
                String days=s.getString(8);
                String stat=s.getString(9);
                String tbdata[]={pid,origin,destination,name1,phone1,phone2,c,days,stat};
                DefaultTableModel d1=(DefaultTableModel)firstTable.getModel();
                d1.addRow(tbdata);
            }
        }catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null,ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        firstTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        secondTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pid = new javax.swing.JLabel();
        o1 = new javax.swing.JLabel();
        dest1 = new javax.swing.JLabel();
        content1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(253, 153, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Take More Orders");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 920, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 60));

        jPanel2.setBackground(new java.awt.Color(0, 0, 153));

        firstTable.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        firstTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Package Id", "Origin", "Destination", "Senders Name", "Senders Number", "Receivers Number", "Content", "Delivery Time", "Status"
            }
        ));
        firstTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                firstTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(firstTable);

        secondTable.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        secondTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Package Id", "Origin", "Destination", "Senders Name", "Senders Number", "Receivers Number", "Content", "Delivery Time", "Status"
            }
        ));
        secondTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                secondTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(secondTable);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 255, 255));
        jLabel2.setText("Package Id ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 255, 255));
        jLabel3.setText("Origin");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 255, 255));
        jLabel4.setText("Destination");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 255, 255));
        jLabel5.setText("Content");

        pid.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        pid.setForeground(new java.awt.Color(255, 255, 0));
        pid.setText("jLabel6");

        o1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        o1.setForeground(new java.awt.Color(255, 255, 0));
        o1.setText("jLabel7");

        dest1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        dest1.setForeground(new java.awt.Color(255, 255, 0));
        dest1.setText("jLabel8");

        content1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        content1.setForeground(new java.awt.Color(255, 255, 0));
        content1.setText("jLabel9");

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Add Order");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 255, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Confirm Order");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 0, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("Move Back ");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(41, 41, 41))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(dest1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(o1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 224, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(80, 80, 80)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(65, 65, 65))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(content1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3)
                                .addGap(233, 233, 233))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(38, 38, 38)
                        .addComponent(pid)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(pid))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(o1)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dest1)
                            .addComponent(jLabel4))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(content1)
                            .addComponent(jLabel5)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 940, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void firstTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_firstTableMouseClicked
         DefaultTableModel d1=(DefaultTableModel)firstTable.getModel();
          
          String pid1=d1.getValueAt(firstTable.getSelectedRow(),0).toString();
          String o11=d1.getValueAt(firstTable.getSelectedRow(),1).toString();
        String d11=d1.getValueAt(firstTable.getSelectedRow(),2).toString();
        String c2=d1.getValueAt(firstTable.getSelectedRow(),6).toString();
                  
        pid.setText(pid1);
        o1.setText(o11);
        dest1.setText(d11);
        content1.setText(c2);
        
        
    }//GEN-LAST:event_firstTableMouseClicked

    private void secondTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_secondTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_secondTableMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
      
        if(firstTable.getSelectedRowCount()==1)
           { DefaultTableModel d1=(DefaultTableModel)firstTable.getModel();
                String pid=d1.getValueAt(firstTable.getSelectedRow(),0).toString();
                String ori=d1.getValueAt(firstTable.getSelectedRow(),1).toString();
               String d11=d1.getValueAt(firstTable.getSelectedRow(),2).toString();
               String n1=d1.getValueAt(firstTable.getSelectedRow(),3).toString();
               String phone1=d1.getValueAt(firstTable.getSelectedRow(),4).toString();
               String phone2=d1.getValueAt(firstTable.getSelectedRow(),5).toString();
        String c2=d1.getValueAt(firstTable.getSelectedRow(),6).toString();
        String days=d1.getValueAt(firstTable.getSelectedRow(),7).toString();
       String stat=d1.getValueAt(firstTable.getSelectedRow(),8).toString();
      String tbdata[]={pid,ori,d11,n1,phone1,phone2,c2,days,stat};
              DefaultTableModel s1=(DefaultTableModel)secondTable.getModel();
                s1.addRow(tbdata);
                JOptionPane.showMessageDialog(null,"RECORD ADDED SUCCESSFULLY!");
                firstTable.getSelectionModel().clearSelection();
           }
        else
        {
            JOptionPane.showMessageDialog(null,"NO RECORD SELECTED!!");
        }
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
      DefaultTableModel d1=(DefaultTableModel)secondTable.getModel();
      if(secondTable.getRowCount()==1)
       {
        String pid=d1.getValueAt(secondTable.getSelectedRow(),0).toString();
        String o1=d1.getValueAt(secondTable.getSelectedRow(),1).toString();
        String d11=d1.getValueAt(secondTable.getSelectedRow(),2).toString();
        String n1=d1.getValueAt(secondTable.getSelectedRow(),3).toString();
        String phone1=d1.getValueAt(secondTable.getSelectedRow(),4).toString();
        String phone2=d1.getValueAt(secondTable.getSelectedRow(),5).toString();
        String c2=d1.getValueAt(secondTable.getSelectedRow(),6).toString();
        String days=d1.getValueAt(secondTable.getSelectedRow(),7).toString();
       String stat=d1.getValueAt(secondTable.getSelectedRow(),8).toString();
       
       try
       {
           String q1="INSERT INTO `employee_orders`(`emp_uname`, `prod_id`, `origin`, `destination`, `sender_name`, `sender_no`, `receiver_no`, `content`, `days`, `status`) VALUES (?,?,?,?,?,?,?,?,?,?)";
       c1=(Connection) MyConnection.connect();
       pst=c1.prepareStatement(q1);
       pst.setString(1,eid);
       pst.setString(2,pid);
       pst.setString(3,o1);
       pst.setString(4,d11);
       pst.setString(5,n1);
       pst.setString(6,phone1);
       pst.setString(7,phone2);
       pst.setString(8,c2);
       pst.setString(9,days);
       pst.setString(10,"Pending");
       pst.executeUpdate();
       JOptionPane.showMessageDialog(null,"YOUR ORDER HAS BEEN INSERTED IN RECORD!!"); 
       String q2="DELETE FROM `employee_orders` WHERE emp_uname='"+e+"'"+" AND prod_id='"+pid+"'";
       pst=c1.prepareStatement(q2);
       pst.execute();
       this.dispose();
           
       }catch(Exception m)
       {
           JOptionPane.showMessageDialog(null,m);
       }
       }
       else
           JOptionPane.showMessageDialog(null,"NO ORDER SELECTED TO SAVE!!");
       
           
      
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
       new Emp_menu(eid).setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jButton3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TakeMoreOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TakeMoreOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TakeMoreOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TakeMoreOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
               // new TakeMoreOrders().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel content1;
    private javax.swing.JLabel dest1;
    private javax.swing.JTable firstTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel o1;
    private javax.swing.JLabel pid;
    private javax.swing.JTable secondTable;
    // End of variables declaration//GEN-END:variables
}
